version: 2
jobs:
  build:
    docker:
      - image: beevelop/android:latest

    working_directory: /opt/workspace/

    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx1400m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"

    steps:
      - checkout

      - restore_cache:
          key: homeassistant-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - run:
          name: Setup environment
          command: .circleci/setup.sh

      - run:
          name: Compile apks
          command: ./gradlew --no-daemon assembleRelease

      - store_artifacts:
          path: app/build/outputs/apk/fdroid/release/
          destination: apks/

      - store_artifacts:
          path: app/build/outputs/apk/gms/release/
          destination: apks/

      - store_artifacts:
          path: app/build/outputs/mapping/gms/release/mapping.txt
          destination: mappings/mapping-gms.txt

      - store_artifacts:
          path: app/build/outputs/mapping/fdroid/release/mapping.txt
          destination: mappings/mapping-fdroid.txt

      - save_cache:
          key: homeassistant-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - "~/.gradle/wrapper/dists/gradle-4.*-all/"
            - "~/.gradle/caches/modules-2/"
            - "~/.gradle/caches/4.*/"
            - "~/.gradle/caches/build-cache-1/"
            - "./.gradle/buildOutputCleanup"
            - "./.gradle/4.*/"
            - "~/.m2"